### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get your app on F-Droid. You can later add a button for Google Play the same way :
`[Get it on Google Play]()`

### CODE REVIEW

**Comment by XilinJia** [comment]
Thank you

**Comment by XilinJia** [comment]
@Poussinou Did you help launch it on f-droid?  Maybe a question for you:  the images shown on f-droid are not the same as on my readme nor as those in the image folder of the project.  Do you know how those are there?

**Comment by XilinJia** [comment]
Got it.  Some from the old play folder were pulled.  I removed the play folder and upped with a new release.  Guess f-droid will automatically update accordingly?

**Comment by Poussinou** [comment]
Now that you removed this old folder, yes normally the screenshots [here](https://github.com/Ifsttar/NoiseCapture/tree/master/fastlane/metadata/android/en-US/images/phoneScreenshots) will appear on F-Droid if I'm not mistaken.

F-Droid will indeed update [automatically](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mdiqentw.lifedots.yml#L29)  :)

**Pull request merged**
